create table tb_districts (id bigint generated by default as identity, info varchar(255), is_leaking boolean, name varchar(255), primary key (id))
create table tb_streets (id bigint generated by default as identity, info varchar(255), is_leaking boolean, leaking_date timestamp, name varchar(255), district_id bigint, primary key (id))
alter table tb_streets add constraint FK763sa9b4jehej2d5mm1e72g04 foreign key (district_id) references tb_districts
