version: "3"

services:
  db:
    image: postgres
    container_name: db
    ports: 
       - "5432:5432"
    environment: 
       - POSTGRES_PASSWORD="12345"
    volumes: 
      - /home/igor/develop/postgresql/data:/var/lib/postgresql/data
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/optimusapi
